name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Verify build output
      run: |
        if [ ! -d "dist" ]; then
          echo "❌ Build failed: dist directory not found"
          exit 1
        fi
        
        # Check for essential output files
        required_files=("dist/index.js" "dist/server.js" "dist/loop.js" "dist/energy.js" "dist/intelligent-model.js" "dist/inbox.js" "dist/config.js")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Build failed: $file not found"
            exit 1
          fi
        done
        
        echo "✅ Build verification successful - all output files present"

    - name: Run build check script
      run: npm run check-build
